version: '3.8'

services:
  app-with-floatie:
    build:
      context: ../..
      dockerfile: examples/embedded/Dockerfile
    ports:
      - "8080:8080"  # App port
      - "8000:8000"  # App metrics port
      - "9090:9090"  # Floatie metrics port
    volumes:
      - /sys/kernel/debug:/sys/kernel/debug
      - /sys/fs/bpf:/sys/fs/bpf
      - /sys/fs/cgroup:/sys/fs/cgroup
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE
      - BPF
    security_opt:
      - apparmor:unconfined
    pid: host  # Required to access host PID namespace

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus